# Generated by Django 5.2.11 on 2026-08-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen libre de derechos (Unsplash, Pexels, etc.)', max_length=500, null=True),
        ),
    ]
